#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 00d1c6c7-442a-44e7-a59e-af455ea52dde
# Source File: C:\Users\kclack\Documents\GitHub\AGUIToolset\AGUIToolset.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
6CgAAB+LCAAAAAAABADlml1v4jgUhu9Xmv9g5RpBEhI+JIjU0umoWphWA2X3rnISw2RqbOQ40zK/
fpwPWCiBOCFkQKtWVQM+Oa/tJ8evk/S+IYf+RGx1BzkE4h/fo6Sv6HVNsT79BUDvkXlzj0B872H0
FS6QdfPl+WFCKfYRry/9Wa+x1yKOs38ghwO+WqK+Ml75HC3q/3jEpW9+/Z6yRfy3BtK+qoFpIsSo
q+FPDQwCzAOG+gQFnEFcA0+BjT3nb7Sa0FdE+na7DU3HbGndpoHUTlcBREjpKzNxvlvIKJlScvNL
nEEBzncPu0zEKANKOBM9ibsqRD8xukSMr5Lgm4DTsQMxuvMWiISCRFOtWQN6q9dYt82KHVEXKda9
SJUZM8AeInzs/RIBmqHrNWCa2ZnCMVesvY5mxk3QO1esjJjPP4WiJGBIoZuS6CX8vNeIWq7Dsmf/
C6PB8pa+n52AeZjIpu/NYzO/PzpD6kAuBChW06yBpqHvjc1+zAgycSUoVqsGkl+JoHj6NiolIp6g
63pknjNPglWzLbDSzI5ExATaD8RF74ol03nReszpUqAORW2QCYj4m47ACHqEIwKJkxqWzdJtwDkl
ZyfJjtLcIYhxCMfRUnIcKU0zhQ4zbVgLUnWIq4+apUITVFqCFEMu2X+oGHLto7nPKevZR1PPDyAe
8xVGt9B5HVBMmWJNWHDgDNvlS1RX53V/RF6iz3frl4hsxNhdLIZP9A2xx/tZcQi74fyacvNVAoNr
wWcnMK2EHiIwEgUeZ3KqygRwPRxXjR8pTl+7/QfoI2eHT66k78AnJ6p89kh56A2hjfDZycNhljHC
Qsx0lJe8yI9HE3t4wA6v1wKFVu7VWo1YVXOwutPDPKxqndRNyXFWtRysxqKAcGtpFq0AMgO6sGkV
/n86irXnBSbUATkXRvszgTZGbiFy9K5aTZlbdzMHNYahhjubnNQc4Hm72MRKkBtFDL5DMg9Hb63w
Je3rjCr08fAC95f6KftLrVPR/lImTQn7SyPf/jKtEpW0v/yGfBowB4EICP8KNpjP3MNiLNfCI90n
uny9sp1mmvi8pqsrt2QWM12JQLDLReUWLG2cyvNjlS2ubP6/WFzX3Tz74ppaCK/BkMcgFytWJ1vz
/AicZM23+5qDCF1vFzDpkrVw26Qn+g5WtuvzVtop3kqX8SIlWCsZE1OGtZK8GX+En5Ks1ZDOwQPh
FKQ/O7o8ZxVfH+PAPuXOffhYzpC7x1iCn9pIvqjbpkmhkZVVpnHaDMgVuiU/sIee/4fMkml0xEop
R8VJ4Ca9zOWVOgW8UmodvGyvFBVKwa7vMG/Jo/cJqvRKuhki0K3ILO13No9ZUltnvqMZyQNZ+i7+
QYxYhD0yoZnvthwnI9ystORmuIRFbVvz2de1PAY6EgaOOJrzrm3b4yK1vO0c7h7c+D5aCI6Qv26b
fLKyFr5DGfbsEljsNTZn/Zglpr+KHKVfYdkZw7flqknE4JtY+IvkUpszc9aeaZprqrAJs3P9u8CV
9GlAGSo/0eYwRr7X2H6z0foNDUKJ6egoAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.124
     Generated on:       7/22/2016 2:07 PM
     Generated by:       kclack
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2016
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-AGUIToolset_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formBaronVonAzure = New-Object 'System.Windows.Forms.Form'
	$groupbox3 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonDeallocate = New-Object 'System.Windows.Forms.Button'
	$buttonPowerOFf = New-Object 'System.Windows.Forms.Button'
	$buttonPowerOn = New-Object 'System.Windows.Forms.Button'
	$labelSelectVM = New-Object 'System.Windows.Forms.Label'
	$VMSelect = New-Object 'System.Windows.Forms.ComboBox'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonUtilizeResourceGroup = New-Object 'System.Windows.Forms.Button'
	$rgSelect = New-Object 'System.Windows.Forms.ComboBox'
	$labelSelectResoureGroup = New-Object 'System.Windows.Forms.Label'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonSelectSub = New-Object 'System.Windows.Forms.Button'
	$subList = New-Object 'System.Windows.Forms.ComboBox'
	$labelAzureSubscriptions = New-Object 'System.Windows.Forms.Label'
	$buttonLoginToAzure = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formBaronVonAzure_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$buttonLoginToAzure_Click={
		#TODO: Place custom script here
		Login-AzureRmAccount
		Add-AzureAccount
		
		$azureSubs = (get-AzureSubscription).SubscriptionName
		Load-ComboBox -ComboBox $subList -Items $azureSubs
	}
	
	#region Control Helper Functions
	function Load-ComboBox 
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
	
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
	
		.PARAMETER  ComboBox
			The ComboBox control you want to add items to.
	
		.PARAMETER  Items
			The object or objects you wish to load into the ComboBox's Items collection.
	
		.PARAMETER  DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER  Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red" -Append
			Load-ComboBox $combobox1 "White" -Append
			Load-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Load-ComboBox $combobox1 (Get-Process) "ProcessName"
	#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if(-not $Append)
		{
			$ComboBox.Items.Clear()	
		}
		
		if($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ComboBox.BeginUpdate()
			foreach($obj in $Items)
			{
				$ComboBox.Items.Add($obj)	
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)	
		}
	
		$ComboBox.DisplayMember = $DisplayMember	
	}
	#endregion
	
	$buttonSelectSub_Click = {
		#setting the active azure subsctption to the current item in the combo box when pressed
		$activesub = $subList.Text
		#running the powershell to set the current subsciption we will be working with for the remainder of utilizing this tool.
		Select-AzureSubscription -SubscriptionName  $($activesub) -Current
		$azureRG = (find-azurermresourcegroup).name
		#loading the next combo box with the list of resource groups utilized by the active azure subscription.
		Load-ComboBox -ComboBox $rgSelect -Items $azureRG
		
		
	}
	
	$buttonUtilizeResourceGroup_Click={
		$activeRG = $rgSelect.Text
		$vmselection= (Find-AzureRmResource -ResourceGroupName $activeRG -ResourceType Microsoft.Compute/virtualMachines -ApiVersion 2015-11-01).name
		Load-ComboBox -ComboBox $VMSelect -Items $vmselection
		
	}
	
	$VMSelect_SelectedIndexChanged={
		
		
	}
	
	$buttonPowerOn_Click={
		$poweronVM = $VMSelect.Text
		
		Invoke-AzureRmResourceAction -ResourceGroupName $rgSelect.Text -ResourceType Microsoft.Compute/virtualMachines -ResourceName $poweronVM -Action start -ApiVersion 2016-03-30 -Force
		
	}
	
	$buttonPowerOFf_Click={
		#TODO: Place custom script here
		$poweroffVM = $VMSelect.Text
		
		Invoke-AzureRmResourceAction -ResourceGroupName $rgSelect.Text -ResourceType Microsoft.Compute/virtualMachines -ResourceName $poweroffVM -Action powerOff -ApiVersion 2016-03-30 -Force
		
	}
	
	$buttonDeallocate_Click={
		#TODO: Place custom script here
		$deallocateVM = $VMSelect.Text
		
		Invoke-AzureRmResourceAction -ResourceGroupName $rgSelect.Text -ResourceType Microsoft.Compute/virtualMachines -ResourceName $deallocateVM -Action deallocate -ApiVersion 2016-03-30 -Force
		
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formBaronVonAzure.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonDeallocate.remove_Click($buttonDeallocate_Click)
			$buttonPowerOFf.remove_Click($buttonPowerOFf_Click)
			$buttonPowerOn.remove_Click($buttonPowerOn_Click)
			$VMSelect.remove_SelectedIndexChanged($VMSelect_SelectedIndexChanged)
			$buttonUtilizeResourceGroup.remove_Click($buttonUtilizeResourceGroup_Click)
			$buttonSelectSub.remove_Click($buttonSelectSub_Click)
			$buttonLoginToAzure.remove_Click($buttonLoginToAzure_Click)
			$formBaronVonAzure.remove_Load($formBaronVonAzure_Load)
			$formBaronVonAzure.remove_Load($Form_StateCorrection_Load)
			$formBaronVonAzure.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formBaronVonAzure.SuspendLayout()
	$groupbox3.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# formBaronVonAzure
	#
	$formBaronVonAzure.Controls.Add($groupbox3)
	$formBaronVonAzure.Controls.Add($groupbox2)
	$formBaronVonAzure.Controls.Add($groupbox1)
	$formBaronVonAzure.AutoScaleDimensions = '13, 26'
	$formBaronVonAzure.AutoScaleMode = 'Font'
	$formBaronVonAzure.ClientSize = '1422, 556'
	$formBaronVonAzure.Name = 'formBaronVonAzure'
	$formBaronVonAzure.Text = 'BaronVonAzure'
	$formBaronVonAzure.add_Load($formBaronVonAzure_Load)
	#
	# groupbox3
	#
	$groupbox3.Controls.Add($buttonDeallocate)
	$groupbox3.Controls.Add($buttonPowerOFf)
	$groupbox3.Controls.Add($buttonPowerOn)
	$groupbox3.Controls.Add($labelSelectVM)
	$groupbox3.Controls.Add($VMSelect)
	$groupbox3.Location = '35, 342'
	$groupbox3.Margin = '6, 6, 6, 6'
	$groupbox3.Name = 'groupbox3'
	$groupbox3.Padding = '6, 6, 6, 6'
	$groupbox3.Size = '1372, 158'
	$groupbox3.TabIndex = 2
	$groupbox3.TabStop = $False
	$groupbox3.Text = 'VM Maintenance'
	#
	# buttonDeallocate
	#
	$buttonDeallocate.Location = '1150, 52'
	$buttonDeallocate.Margin = '6, 6, 6, 6'
	$buttonDeallocate.Name = 'buttonDeallocate'
	$buttonDeallocate.Size = '162, 46'
	$buttonDeallocate.TabIndex = 4
	$buttonDeallocate.Text = 'Deallocate'
	$buttonDeallocate.UseVisualStyleBackColor = $True
	$buttonDeallocate.add_Click($buttonDeallocate_Click)
	#
	# buttonPowerOFf
	#
	$buttonPowerOFf.Location = '962, 54'
	$buttonPowerOFf.Margin = '6, 6, 6, 6'
	$buttonPowerOFf.Name = 'buttonPowerOFf'
	$buttonPowerOFf.Size = '162, 46'
	$buttonPowerOFf.TabIndex = 3
	$buttonPowerOFf.Text = 'Power Off'
	$buttonPowerOFf.UseVisualStyleBackColor = $True
	$buttonPowerOFf.add_Click($buttonPowerOFf_Click)
	#
	# buttonPowerOn
	#
	$buttonPowerOn.Location = '772, 54'
	$buttonPowerOn.Margin = '6, 6, 6, 6'
	$buttonPowerOn.Name = 'buttonPowerOn'
	$buttonPowerOn.Size = '162, 46'
	$buttonPowerOn.TabIndex = 2
	$buttonPowerOn.Text = 'Power On'
	$buttonPowerOn.UseVisualStyleBackColor = $True
	$buttonPowerOn.add_Click($buttonPowerOn_Click)
	#
	# labelSelectVM
	#
	$labelSelectVM.AutoSize = $True
	$labelSelectVM.Location = '12, 62'
	$labelSelectVM.Margin = '6, 0, 6, 0'
	$labelSelectVM.Name = 'labelSelectVM'
	$labelSelectVM.Size = '118, 26'
	$labelSelectVM.TabIndex = 1
	$labelSelectVM.Text = 'Select VM '
	#
	# VMSelect
	#
	$VMSelect.FormattingEnabled = $True
	$VMSelect.Location = '290, 54'
	$VMSelect.Margin = '6, 6, 6, 6'
	$VMSelect.Name = 'VMSelect'
	$VMSelect.Size = '440, 34'
	$VMSelect.TabIndex = 0
	$VMSelect.add_SelectedIndexChanged($VMSelect_SelectedIndexChanged)
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonUtilizeResourceGroup)
	$groupbox2.Controls.Add($rgSelect)
	$groupbox2.Controls.Add($labelSelectResoureGroup)
	$groupbox2.Location = '35, 182'
	$groupbox2.Margin = '6, 6, 6, 6'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Padding = '6, 6, 6, 6'
	$groupbox2.Size = '1372, 148'
	$groupbox2.TabIndex = 1
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Resource Groups'
	#
	# buttonUtilizeResourceGroup
	#
	$buttonUtilizeResourceGroup.Location = '962, 22'
	$buttonUtilizeResourceGroup.Margin = '6, 6, 6, 6'
	$buttonUtilizeResourceGroup.Name = 'buttonUtilizeResourceGroup'
	$buttonUtilizeResourceGroup.Size = '162, 90'
	$buttonUtilizeResourceGroup.TabIndex = 2
	$buttonUtilizeResourceGroup.Text = 'Utilize Resource Group'
	$buttonUtilizeResourceGroup.UseVisualStyleBackColor = $True
	$buttonUtilizeResourceGroup.add_Click($buttonUtilizeResourceGroup_Click)
	#
	# rgSelect
	#
	$rgSelect.FormattingEnabled = $True
	$rgSelect.Location = '290, 54'
	$rgSelect.Margin = '6, 6, 6, 6'
	$rgSelect.Name = 'rgSelect'
	$rgSelect.Size = '440, 34'
	$rgSelect.TabIndex = 1
	#
	# labelSelectResoureGroup
	#
	$labelSelectResoureGroup.AutoSize = $True
	$labelSelectResoureGroup.Location = '12, 54'
	$labelSelectResoureGroup.Margin = '6, 0, 6, 0'
	$labelSelectResoureGroup.Name = 'labelSelectResoureGroup'
	$labelSelectResoureGroup.Size = '227, 26'
	$labelSelectResoureGroup.TabIndex = 0
	$labelSelectResoureGroup.Text = 'Select Resoure Group'
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonSelectSub)
	$groupbox1.Controls.Add($subList)
	$groupbox1.Controls.Add($labelAzureSubscriptions)
	$groupbox1.Controls.Add($buttonLoginToAzure)
	$groupbox1.Location = '35, 28'
	$groupbox1.Margin = '6, 6, 6, 6'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Padding = '6, 6, 6, 6'
	$groupbox1.Size = '1372, 142'
	$groupbox1.TabIndex = 0
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Log Into Azure'
	#
	# buttonSelectSub
	#
	$buttonSelectSub.Location = '1122, 43'
	$buttonSelectSub.Margin = '6, 6, 6, 6'
	$buttonSelectSub.Name = 'buttonSelectSub'
	$buttonSelectSub.Size = '162, 46'
	$buttonSelectSub.TabIndex = 3
	$buttonSelectSub.Text = 'Select Sub'
	$buttonSelectSub.UseVisualStyleBackColor = $True
	$buttonSelectSub.add_Click($buttonSelectSub_Click)
	#
	# subList
	#
	$subList.FormattingEnabled = $True
	$subList.Location = '548, 56'
	$subList.Margin = '6, 6, 6, 6'
	$subList.Name = 'subList'
	$subList.Size = '448, 34'
	$subList.TabIndex = 2
	#
	# labelAzureSubscriptions
	#
	$labelAzureSubscriptions.AutoSize = $True
	$labelAzureSubscriptions.Location = '258, 59'
	$labelAzureSubscriptions.Margin = '6, 0, 6, 0'
	$labelAzureSubscriptions.Name = 'labelAzureSubscriptions'
	$labelAzureSubscriptions.Size = '206, 26'
	$labelAzureSubscriptions.TabIndex = 1
	$labelAzureSubscriptions.Text = 'Azure Subscriptions'
	#
	# buttonLoginToAzure
	#
	$buttonLoginToAzure.Location = '40, 60'
	$buttonLoginToAzure.Margin = '6, 6, 6, 6'
	$buttonLoginToAzure.Name = 'buttonLoginToAzure'
	$buttonLoginToAzure.Size = '162, 46'
	$buttonLoginToAzure.TabIndex = 0
	$buttonLoginToAzure.Text = 'Login to Azure'
	$buttonLoginToAzure.UseVisualStyleBackColor = $True
	$buttonLoginToAzure.add_Click($buttonLoginToAzure_Click)
	$groupbox1.ResumeLayout()
	$groupbox2.ResumeLayout()
	$groupbox3.ResumeLayout()
	$formBaronVonAzure.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formBaronVonAzure.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formBaronVonAzure.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formBaronVonAzure.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formBaronVonAzure.ShowDialog()

} #End Function

#Call the form
Call-AGUIToolset_psf | Out-Null
